name: update-rust
on:
  repository_dispatch:
    types:
      - newreleases.io/rust

jobs:
  update-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create new branch
        run: git checkout -b "newreleases.io/rust-${{ github.event.client_payload.version }}"
      - name: Replace rust version string
        run: sed -i 's/VERSION_RUST=[0-9]+\.[0-9]+\.[0-9]+/VERSION_RUST=${{ github.event.client_payload.version }}/' Dockerfile
      - name: Add, commit and push changes
        run: |
          git add Dockerfile 
          git commit -m "Updated rust version to ${{ github.event.client_payload.version }}"
          git push -u origin newreleases.io/rust-${{ github.event.client_payload.version }}
      - name: create pull request
        run: gh pr create --title "Update rust version to ${{ github.event.client_payload.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      